datadir: 'data/KNMI.txt.tsv'
file_assignemnt_1: '/data/datasets/Programming1/eeg_data.csv'
file_assessment_2: 'glucose.json'
careplans: '../../../Data/10k_synthea_covid19_csv/careplans.csv'
conditions: '../../../Data/10k_synthea_covid19_csv/conditions.csv'
encounters: '../../../Data/10k_synthea_covid19_csv/encounters.csv'
observations: '../../../Data/10k_synthea_covid19_csv/observations.csv'
patients: '../../../Data/10k_synthea_covid19_csv/patients.csv'