datadir: 'data/KNMI.txt.tsv'
file_assignemnt_1: '/data/datasets/Programming1/eeg_data.csv'
file_assessment_2: '/data/datasets/Programming1/glucose.json'
careplans: '10k_synthea_covid19_csv/careplans.csv'
conditions: '10k_synthea_covid19_csv/conditions.csv'
encounters: '10k_synthea_covid19_csv/encounters.csv'
observations: '10k_synthea_covid19_csv/observations.csv'
patients: '10k_synthea_covid19_csv/patients.csv'
